/*
 * Copyright 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

apply plugin: 'com.android.library'

dependencies {
    implementation project(':camerax:camera-core')
    implementation("androidx.annotation:annotation:1.2.0")
    implementation("androidx.annotation:annotation-experimental:1.1.0")
    implementation("androidx.core:core:1.3.1@aar")
    implementation("androidx.concurrent:concurrent-futures:1.0.0")
    implementation("com.google.auto.value:auto-value-annotations:1.8.1")
    annotationProcessor 'com.google.auto.value:auto-value:1.10.4'
    implementation("androidx.lifecycle:lifecycle-livedata:2.4.0")
}

android {
    namespace 'androidx.camera.camera_camera2'
    compileSdk = rootProject.ext.compileSdkVersion
    ndkVersion = rootProject.ext.ndkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName version
        multiDexEnabled true
    }

    buildTypes.all {
        consumerProguardFiles "proguard-rules.pro"
    }

    lintOptions {
        enable 'CameraXQuirksClassDetector'
    }

    // Use Robolectric 4.+
    testOptions.unitTests.includeAndroidResources = true
    namespace "androidx.camera.camera2"
}

//androidx {
//    name = "Jetpack Camera Library Camera2 Implementation/Extensions"
//    publish = Publish.SNAPSHOT_AND_RELEASE
//    mavenGroup = LibraryGroups.CAMERA
//    inceptionYear = "2019"
//    description = "Camera2 implementation and extensions for the Jetpack Camera Library, a " +
//            "library providing a consistent and reliable camera foundation that enables great " +
//            "camera driven experiences across all of Android."
//}
